# Generated by Django 3.1.7 on 2021-03-10 17:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import insightapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('insightapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=insightapp.models.upload_image_path_profile)),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Numero muodossa: '+3581234567890'.", regex='^\\+?1?\\d{9,14}$')])),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('post_number', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length mus be 5', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
