# Generated by Django 3.1.7 on 2021-03-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insightapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruokalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viisi', models.CharField(max_length=100)),
                ('kuusi', models.CharField(max_length=100)),
                ('seitseman', models.CharField(max_length=100)),
                ('kahdeksan', models.CharField(max_length=100)),
                ('yhdeksan', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruokalistas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RavinVaikutu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kymenen', models.CharField(max_length=100)),
                ('yksitoista', models.CharField(max_length=100)),
                ('kaksitoista', models.CharField(max_length=100)),
                ('kolmetoista', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ravinvaikutus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perustiedot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yksi', models.CharField(max_length=100)),
                ('kaksi', models.CharField(max_length=100)),
                ('kolme', models.CharField(max_length=100)),
                ('nelja', models.CharField(max_length=100)),
                ('viisi', models.CharField(max_length=100)),
                ('kuusi', models.CharField(max_length=100)),
                ('seitseman', models.CharField(max_length=100)),
                ('kahdeksan', models.CharField(max_length=100)),
                ('yhdeksan', models.CharField(max_length=100)),
                ('kymenen', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perustiedots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asiointi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yksi', models.CharField(max_length=100)),
                ('kaksi', models.CharField(max_length=100)),
                ('kolme', models.CharField(max_length=100)),
                ('nelja', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asiointis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
