# Generated by Django 3.1.7 on 2021-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insightapp', '0003_asiointi_perustiedot_ravinvaikutu_ruokalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
