phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker-compose build"
      - "docker tag insightspace_db_1 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend_postgres"
      - "docker tag insightspace_app_1 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend"
      - "docker tag insightspace_proxy_1 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend_proxy"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend"
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend_postgres"
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_backend_proxy"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiVDFybU9TZk9aNTBmdkhCZlFKYWVaWDc5WWgvUnF6elFZSktaVWM0M0dFWFptWVJXNzVYWXpianRpZTdLTHphSjdQWlBFWFlXWVpvdDJMM0RXMDZXcUV0M3B3OTZLdjBlOERSNmtuMEJrMUQxblVZbVg1S2EyY3RVTHMxMzlrcEhtNHdaWkl6SEw3NmMzU0g0WXBZRUREUEcxM3U2L2lwWVBkcXc3MWpBRWRyb1JFallTcHZnbkhDWWVVbHZSTVl5alZraC8zNHhQVE9qQlBaZFFXYzU2Q25DSE94R2R5NDZITVVUUXpReWJ2eE1QMWlqd1pBUzU1NHVKWmJjVEd6c1poNnBJRzJJeXZTUHFBaVRSWWZIVDFXYUR4UTZtUCtycUx1Y2RGQWdoVmQ1TGJXaDdtNzRJSTg3TDBtdjRRQ3VMWFBxU0NSQ3BhSFRuMXRmWFRhcWRPaU1UL2VvSDJlZFQ3Z1l3bndYa0Y4NldsRzNscGl5WGtQdjF6K2NUbmpJWG5HL0k3b2RPam9Id2V2MVRxb1BaSENCa0h6UVh5cWRMeEtONVhLRW1Ca2FueG4vdGJNTGJkZFpGaGp2dDFSVVdYWjlab3BPd250Y1NRS3JVekZMNk80REtzSzYzRlhTUlpSRGRZMDdPWDFYOWZvQTZhSTZJWEZEVlpqSDREbDdmcmo1dnRuUmdqWTdzOVJ5cGozYUV6SlgrSjgyTTBzMDdCVUZMVHpHWDBHa2NZMlJLT2lTdE01Y1poYkFlbWRFNjRkbmFNbHRuR0REOXVoY3RGT1FpeUIzUDBXNUNsb0xYZloxbzhiN0hmb0F0akhuSDByZWo4by9wa3dQTHk0elpKUzQ2NjhhYVVkQmsxcTVPcm9UZ3BZdXQ0dVRYd2xmSG1hamYxNVdWeE1yWVRVOXJEZlNiU1FzT2RmejJJank0eVBUTHFRU3ZNUzZ3NVhWZExPV0FkUzVhNXRZa3hVN0FadjJQQUx2NytPYXJuQ01wUkRjZWZHemkyN0RheFV6S2lEck1BNlFjZEdITXFFdUw5Z2hvczZESE42czhYSWd5aEFMQU90aFpYVEc0bGFralQrUFlwUzJuMWwwdXAzWnRRTkRLVzhHZGlLTWxNVFlzSkY0cE03N1lXTFJPVm1vWThqeHNXM2RndEFERlpsR25sN3piNXZZUkc0RXNTWGNQRnJnSjZ2ZXFvbXRJK1ZMb2lQVzlxZDFhUzd0ZERVazdTamRJQ3JxNXVTdS9TcUJOM0htd1hmQUtMUi9zcW5MeHJmQ1hYSFZLNkJIR0VOT3hMT3JoWDlaR0hUWkF5QjlkWTV6ZFRlUWFEdU1pQVhNQ1NkTmxHU1VVOVBOM25EcVRHMlN1ZFB3VTRaMGtUK29SRlVpa3VibGltZFZvV1M4V3Q0Rjh1MERqZnNZaFlqK1dWZkJMb3JyRDJUNWc1VmZORlIySlJST29jZDJ0d0hEZElqODh6aUthRE1wMDE3ckJRPT0iLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdGS0llSjlTVFFaTTdqd3FjOEVILzFEQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNQ3hqbjgvNGdVWFJrMjlJS0FnRVFnRHNCM3BFR0ZKdUFHY3MxZUVsK3JIa0M3dTc5T0lEMExjaktTL2N0OW4vemROMXVmY1g3elZwblcrLzg1RVBIbStrWXVPNWVLY3J5b0MybW9RPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MTY2MTY0MjB9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
      - "docker login -u axwdigitaldocker -p 075l2q1O!"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1