version: '3.7'

services:
  app:
    build: 
      context: .
    volumes:
      - static_data:/vol/web
      - ./insightproject:/app
    # env_file:
    #   - ./.env.dev
    depends_on:
      - db
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
  db:
    image: postgres:12.0-alpine 
    volumes: 
      - postgres_data:/var/lib/postgres/data
    
    
    


volumes:
  static_data:
  postgres_data:
  
