version: "3.7"

services: 
  web:
    build: 
      context: .
    volumes:
      - static_data:/static
    env_file: 
      - insightproject/.env
    ports:
      - "8000:8000"
    depends_on: 
      - db
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=insightdb
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=075l2q1O
  nginx:
    build: ./nginx
    volumes: 
      - static_data:/static
    ports: 
      - "80:80"
    depends_on: 
      - web


volumes: 
  static_data: